#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

	while IFS=':' read -r USERNAME GID HOME SHELL uid PASSWORD INFO;
	do
		echo "The user $USERNAME is part of the $GID gang, lives in $HOME and rides $SHELL. $uid's place is protected by the passcode $PASSWORD, more info about the user here: $INFO"
	done < "/etc/passwd"
