#!/usr/bin/env bash
# Displaying Best School 10 times but the 9nth time it prints Hi with a while and if loop
TACOS=0
while [ $TACOS -le 10 ]
do
	if [ $TACOS -eq 9 ]
	then
		echo "Hi"
	else
        echo "Best School"
        fi
       	((TACOS++))
done
