#!/usr/bin/env bash
# Displaying Best School 10 times with a while loop
TACOS=0
while [ $TACOS -lt 10 ]
do
        if [ $TACOS -ne 9 ]
	then
		echo "Best School"
	else
		echo "Hi"
	fi
	((TACOS++))
done
