#!/usr/bin/env bash
# display 10 lines
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
TACOS=0
while [ $TACOS -le 9 ]
do
        if [ $TACOS -eq 3 ]
        then
                echo "bad luck"
	elif [ $TACOS -eq 7 ]
	then
		echo "good luck"
        else
                echo "Best School"
        fi
        ((TACOS++))
done 
