#!/usr/bin/env bash
#print bad luck 4th loop, good luck 8th loop, Best School other

        count=0

        while [ $count -le 9 ]
        do
                if [ $count = 3 ]
                then
                        echo "bad luck"
                elif
                        [ $count = 7 ]
                then    
			echo "good luck"
                else
                        echo "Best School"
                fi
		((count++))
        done

