#!/usr/bin/env bash
# The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

	for tacos in *
		do
			echo "$tacos" | cut -d '-' -f-2
	done
